# Generated by Django 5.1.3 on 2024-12-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_detail',
            field=models.JSONField(null=True),
        ),
    ]
