# Generated by Django 5.1.3 on 2024-12-08 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_alter_booking_booking_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='room_number',
            new_name='room_no',
        ),
    ]
