# Generated by Django 5.1.3 on 2024-12-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_gallery_roomimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomimage',
            name='roomtype',
        ),
        migrations.AddField(
            model_name='roomimage',
            name='roomtype',
            field=models.ManyToManyField(to='rooms.roomtype'),
        ),
    ]
