# Generated by Django 5.1.3 on 2024-12-08 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_remove_roomimage_roomtype_roomimage_roomtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomimage',
            name='roomtype',
        ),
        migrations.AddField(
            model_name='roomimage',
            name='roomtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rooms.roomtype'),
        ),
    ]
