# Generated by Django 5.1.3 on 2024-12-13 05:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_remove_roomimage_roomtype_roomimage_roomtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='roomtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_type_imgs', to='rooms.roomtype'),
        ),
    ]
