# Generated by Django 5.1.3 on 2024-12-09 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_profile_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(upload_to='banner_imgs/')),
            ],
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('mobile', models.IntegerField(blank=True, null=True)),
                ('message', models.TextField(null=True)),
                ('updated_cv', models.FileField(upload_to='cv_files/')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
